### ISSUE TITLE
Progress bars rendering on top of each other?

### ISSUE THREAD

**Issue by alexdrans** [pitaj/multi-progress#7]
```
> node -v
v7.7.3
```

Inside of two classes I'm doing..

```javascript
this.progress = this.prog.newBar(this.formatString, {
  complete: '🔥',
  incomplete: '💩',
  width: 45,
  total: total
});

... 

this.progress.tick()
```

but the bars are being rendered on the same line? Are they meant to be stacked? A screenshot would be nice on this repo.

**Comment by pitaj** [comment]
Closing this because it's old. Let me know if this still happens on the latest version
